/****** Script for SelectTopNRows command from SSMS  ******/

SELECT DP.TRIP_DETAIL.service_change_num, 
operation_date, 
DP.TRIP_DETAIL.day_code,
DP.TRIP_DETAIL.service_rte_num, 
DP.TRIP_DETAIL.express_local_cd, 
--all_trips.day_part_cd,
count (DP.TRIP_DETAIL.trip_id) as trip_count , 
CASE WHEN SCHED_START_TIME_MNTS_AFTER_MIDNT  < 300 THEN 'XNT'
WHEN SCHED_START_TIME_MNTS_AFTER_MIDNT  >= 300 and SCHED_START_TIME_MNTS_AFTER_MIDNT  < 540 THEN 'AM'
WHEN SCHED_START_TIME_MNTS_AFTER_MIDNT  >= 540 and SCHED_START_TIME_MNTS_AFTER_MIDNT  < 900 THEN 'MID'
WHEN SCHED_START_TIME_MNTS_AFTER_MIDNT  >= 900 and SCHED_START_TIME_MNTS_AFTER_MIDNT  < 1140 THEN 'PM'
WHEN SCHED_START_TIME_MNTS_AFTER_MIDNT  >= 1140 and SCHED_START_TIME_MNTS_AFTER_MIDNT  < 1320 THEN 'XEV'
WHEN SCHED_START_TIME_MNTS_AFTER_MIDNT  >= 1320 THEN 'XNT'

END AS day_part_cd

FROM DP.TRIP_DETAIL
--LEFT JOIN (
--select *
--FROM
--DP.ALL_TRIPS 
--WHERE TRIP_KIND_CD = 'S' and SERVICE_CHANGE_NUM IN (223,231, 232,233)) all_trips
--on (DP.TRIP_DETAIL.trip_id = ALL_TRIPS.trip_id
--and DP.TRIP_DETAIL.service_change_num = ALL_TRIPS.service_change_num)
WHERE operation_date between '2023-01-01' and '2023-11-17'

GROUP BY DP.TRIP_DETAIL.service_change_num, 
operation_date, 
DP.TRIP_DETAIL.day_code,
DP.TRIP_DETAIL.service_rte_num, 
DP.TRIP_DETAIL.express_local_cd,
CASE WHEN SCHED_START_TIME_MNTS_AFTER_MIDNT  < 300 THEN 'XNT'
WHEN SCHED_START_TIME_MNTS_AFTER_MIDNT  >= 300 and SCHED_START_TIME_MNTS_AFTER_MIDNT  < 540 THEN 'AM'
WHEN SCHED_START_TIME_MNTS_AFTER_MIDNT  >= 540 and SCHED_START_TIME_MNTS_AFTER_MIDNT  < 900 THEN 'MID'
WHEN SCHED_START_TIME_MNTS_AFTER_MIDNT  >= 900 and SCHED_START_TIME_MNTS_AFTER_MIDNT  < 1140 THEN 'PM'
WHEN SCHED_START_TIME_MNTS_AFTER_MIDNT  >= 1140 and SCHED_START_TIME_MNTS_AFTER_MIDNT  < 1320 THEN 'XEV'
WHEN SCHED_START_TIME_MNTS_AFTER_MIDNT  >= 1320  THEN 'XNT'
END 
ORDER BY 2,4,5